version: '2'
services:
  vpn:
    image: kerneldos/vpn-client:v1.0
    cap_add:
      - ALL
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./openvpn:/vpn

  php:
    image: kerneldos/search:v2.3
    container_name: project
    network_mode: 'service:vpn'
    restart: unless-stopped
    depends_on:
      - vpn
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./.ssh:/root/.ssh
      - ./:/app:delegated
      - ./files:/app/files