version: '2'
services:
  php:
    image: kerneldos/search:v1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./openvpn/certs:/etc/openvpn/certs
      - ./openvpn/client.conf:/etc/openvpn/client.conf
      - /dev/net:/dev/net:z
    cap_add:
      - ALL
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      - '8000:80'
