version: '2'
services:
  vpn:
    image: dperson/openvpn-client
    build:
      context: ./php-8-workspace
      dockerfile: Dockerfile
    cap_add:
      - ALL
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./openvpn:/vpn

  php:
    image: kerneldos/search:v2
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated
      - ./files:/app/files